First Screen - done!
malyshewandrew/Av.by pull request #1
Opened 2023-12-10 19:47 UTC by malyshewandrew

Надеюсь я всё здесь оформил правильно

2023-12-11 16:24 UTC, mishamorochko commented on av.by/CellSearch.swift
> +    func helpers() {
Лучше использовать configureViews(), addSubviews()

2023-12-11 16:24 UTC, mishamorochko commented on av.by/CellSearch.swift
> +        stackView.addArrangedSubview(vinSticker)
addArrangedSubviews Extension

2023-12-11 16:27 UTC, mishamorochko commented on av.by/CellSearch.swift
> +    func configure2(car: Car) {
Нейминг

2023-12-11 16:40 UTC, mishamorochko requested changes

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CellSearch.swift
> +        topSticker.isHidden = true
Вынести в init

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CellSearch.swift
> +            cityLabel.topAnchor.constraint(equalTo: descriptionView.bottomAnchor, constant: 12).isActive = true
Раздели на методы

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CellSearch.swift
> +            cityLabel.topAnchor.constraint(equalTo: descriptionView.bottomAnchor, constant: 12).isActive = true
setEmptyState()

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CellSearch.swift
> +            cityLabel.translatesAutoresizingMaskIntoConstraints = false
ShowAdditionalFeatures()

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CellSearch.swift
> +    @objc func tapOnHideButton() {
private?

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CollectionViewCell.swift
> +final class CollectionViewCell: UICollectionViewCell {
Дать осмысленное название

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CollectionViewCell.swift
> +        addSubview(viewButton)
addSubviews

2023-12-11 16:40 UTC, mishamorochko commented on av.by/CollectionViewCell.swift
> +    @objc func funcTest() {
private/delete

2023-12-11 16:40 UTC, mishamorochko commented on av.by/Main.swift
> +final class Main: UIViewController {
MainListViewController

2023-12-11 16:40 UTC, mishamorochko commented on av.by/Main.swift
> +    @objc func tapButton() {
public?

2023-12-11 16:40 UTC, mishamorochko commented on av.by/Search.swift
> +final class Search: UIViewController {
Нейминг

2023-12-11 16:40 UTC, mishamorochko commented on av.by/Search.swift
> +        title = "\(arrayCars.count) объявлений"
Вынести во ViewDidAppear

2023-12-11 16:40 UTC, mishamorochko commented on av.by/Search.swift
> +        tableView.delegate = self
Вынести в отдельный метод

2023-12-11 21:39 UTC, malyshewandrew commented
Выполнил!
![1](https://github.com/malyshewandrew/av.by/assets/144622587/1ff3a4ad-98ac-4e4b-a995-042df6040310)
![2](https://github.com/malyshewandrew/av.by/assets/144622587/5f621ae5-2fb6-4bc5-b7f0-cc299541ca25)

2023-12-13 21:00 UTC, mishamorochko approved these changes

2023-12-14 13:37 UTC, merged